# Generated by Django 5.0.9 on 2024-11-10 14:30

from django.db import migrations
from django.contrib.auth.models import Group

def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name='Instrutores')
    Group.objects.get_or_create(name='Alunos')
    Group.objects.get_or_create(name='Administradores')

def delete_groups(apps, schema_editor):
    Group.objects.filter(name__in=['Instrutores', 'Alunos', 'Administradores']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('lessons', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
